import { NextRequest, NextResponse } from 'next/server';

const SPOTIFY_BASE = 'https://api.spotify.com/v1';

export async function POST(request: NextRequest) {
  try {
    const { name, trackUris, accessToken, userId } = await request.json();

    if (!name || !trackUris?.length || !accessToken) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Get userId if not supplied
    let uid = userId;
    if (!uid) {
      const userRes = await fetch(`${SPOTIFY_BASE}/me`, {
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      if (!userRes.ok) {
        const err = await userRes.text();
        return NextResponse.json({ error: `Failed to get user: ${err}` }, { status: 500 });
      }
      const user = await userRes.json();
      uid = user.id;
    }

    // Create playlist
    const createRes = await fetch(`${SPOTIFY_BASE}/users/${uid}/playlists`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name,
        description: `Generated by DJ Set Architect — ${new Date().toLocaleDateString()}`,
        public: false,
      }),
    });

    if (!createRes.ok) {
      const err = await createRes.text();
      return NextResponse.json({ error: `Failed to create playlist: ${err}` }, { status: 500 });
    }

    const playlist = await createRes.json();

    // Add tracks in batches of 100 (Spotify limit)
    const batches = [];
    for (let i = 0; i < trackUris.length; i += 100) {
      batches.push(trackUris.slice(i, i + 100));
    }

    for (const batch of batches) {
      const addRes = await fetch(`${SPOTIFY_BASE}/playlists/${playlist.id}/tracks`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ uris: batch }),
      });
      if (!addRes.ok) {
        const err = await addRes.text();
        return NextResponse.json({ error: `Failed to add tracks: ${err}` }, { status: 500 });
      }
    }

    return NextResponse.json({
      playlistId: playlist.id,
      playlistUrl: playlist.external_urls.spotify,
    });

  } catch (e) {
    console.error('Save playlist error:', e);
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'Failed to save playlist' },
      { status: 500 }
    );
  }
}
