// app/api/save-playlist/route.ts
// Creates a new Spotify playlist and adds the generated tracks

import { NextRequest, NextResponse } from 'next/server';
import { createPlaylistAndAddTracks, getCurrentUser } from '@/lib/spotify';

export async function POST(request: NextRequest) {
  try {
    const { name, trackUris, accessToken, userId } = await request.json();

    if (!name || !trackUris?.length || !accessToken) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Get userId if not supplied
    let uid = userId;
    if (!uid) {
      const user = await getCurrentUser(accessToken);
      uid = user.id;
    }

    const playlist = await createPlaylistAndAddTracks(
      uid,
      name,
      trackUris,
      accessToken,
      `Generated by DJ Set Architect — ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`
    );

    return NextResponse.json({
      playlistId: playlist.id,
      playlistUrl: playlist.external_urls.spotify,
    });
  } catch (e) {
    console.error('Save playlist error:', e);
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'Failed to save playlist' },
      { status: 500 }
    );
  }
}
